# Generated by Django 2.2.6 on 2019-10-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='logo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='business_email',
        ),
    ]
