# Generated by Django 2.2.6 on 2019-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_emergencycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='alt_phone_number',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='ambulance_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='fireservice_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='police_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
